
GET http://localhost:8080/getall
Accept: application/json

#### GET request with parameter
#GET https://httpbin.org/get?show_env=1
#Accept: application/json

#DELETE http://localhost:8080/delete
#GET http://localhost:8080/getbyID/101
### GET request with parameter
#GET http://localhost:8080/getbyID?eid=1
#Accept: application/json


## Send POST request with json body
PUT http://localhost:8080/updateEmployee
Content-Type: application/json

{
  "eid": 1,
  "fname": "Testname",
  "salary": 120000
}


#### Send POST request with body as parameters
#POST https://httpbin.org/post
#Content-Type: application/x-www-form-urlencoded
#
#id=999&value=content

